name: Test, Build and Deploy Example to GitHub-Pages
on: [ push ]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      # Setup stuff
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 21
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      # Check and build project
      - run: yarn install
      - run: yarn check
      - run: yarn build
      - run: yarn test

      # Generate example
      - run: yarn workspace example generate:ci
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "./example/out"
      - uses: actions/deploy-pages@v4

      # publish library
      - run: yarn npm publish
        if: github.ref == 'refs/heads/main'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
